version: "3.8"

services:

  app:
    container_name: "app_js"
    build: .
    image: "dennisdf/iot:1.0"
    restart: on-failure
    environment: 
      - NODE_ENV=production
    depends_on: 
      - broker
      - maria_db

  maria_db:
    container_name: "MariaDB"
    image: "mariadb:10.5.9"
    restart: always
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes: 
      - vol-mariadb-data:/var/lib/mysql

  phpmyadmin:
    container_name: "PHPMyAdmin"
    image: "phpmyadmin"
    restart: always
    ports: 
      - "8086:80"
    environment: 
      - PMA_HOST=maria_db
      - PMA_PORT=3306
    depends_on: 
      - maria_db

  broker:
    container_name: "EMQX"
    image: "emqx/emqx:4.2.9"
    restart: on-failure
    environment: 
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=127.0.0.1"
    env_file: ./.config/emqx.env
    depends_on: 
      - maria_db
    ports: 
      - "8883:8883"   #mqtt:ssl
      - "1883:1883"   #mqtt:tcp
      - "11883:11883" #mqtt:tcp
      - "18083:18083" #http:dashboard
      - "8081:8081"   #http:api
      - "8083:8083"   #mqtt:ws
      - "8084:8084"   #mqtt:wss
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
      - vol-emqx-lib:/opt/emqx/lib

  portainer:
    container_name: "Portainer"
    image: "portainer/portainer-ce"
    restart: on-failure
    ports: 
      - "9000:9000"
    volumes: 
      - vol-portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - broker
      - app
      - phpmyadmin
      - maria_db

volumes:
  vol-emqx-data:
    name: emqx-data
  vol-emqx-etc:
    name: emqx-etc
  vol-emqx-log:
    name: emqx-log 
  vol-emqx-lib:
    name: emqx-lib 
  vol-portainer-data:
    name: portainer-data
  vol-mariadb-data:
    name: mariadb-data